<?php
declare(strict_types=1);require __DIR__.'/auth.php';require __DIR__.'/finance-sources.php';require __DIR__.'/secret-config.php';requireLogin(true);header('Content-Type: application/json');
try {
 verifyCsrf($_SERVER['HTTP_X_CSRF_TOKEN']??'');$input=json_decode(file_get_contents('php://input'),true,512,JSON_THROW_ON_ERROR);$prompt=trim($input['prompt']??'');
 if(strlen($prompt)<10)throw new RuntimeException('Please provide a more specific research request.');
 $siteConfig=is_file(__DIR__.'/config.php')?require __DIR__.'/config.php':[];
 $key=openAiApiKey($siteConfig);if(!$key)throw new RuntimeException('OPENAI_API_KEY is not configured on the server.');
 $licensed=queryFinanceSources($prompt);$licensedContext=$licensed?"\nLicensed database results supplied by the server:\n".json_encode($licensed,JSON_THROW_ON_ERROR):'';
 $instructions='Use web search and the supplied licensed finance-database results. Prioritize SEC and regulatory filings, company and investor disclosures, licensed PitchBook and Crunchbase data, other licensed finance databases, then reputable search results. Cross-check material facts. Never invent or estimate undisclosed values. Every record must contain source_name, a valid source_url, and as_of_date. Return one JSON object with a records array. Each record has type (company, ai_company, data_center, pe_firm, vc_firm, spac, vc_investment, pe_ownership), name, category, and a data object. For investments data must include company_name, vc_firm_name, round_name, announced_date, amount, currency and source_url. For ownership data must include company_name, pe_firm_name, acquired_date and source_url. Use null for undisclosed facts.';
 $payload=['model'=>getenv('OPENAI_MODEL')?:'gpt-5-mini','instructions'=>$instructions,'input'=>$prompt.$licensedContext,'tools'=>[['type'=>'web_search']],'text'=>['format'=>['type'=>'json_object']]];
 $ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$key,'Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_THROW_ON_ERROR),CURLOPT_TIMEOUT=>120]);$raw=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_RESPONSE_CODE);if($raw===false)throw new RuntimeException('AI service connection failed.');$response=json_decode($raw,true,512,JSON_THROW_ON_ERROR);if($status>=400)throw new RuntimeException('AI service rejected the request.');
 $text='';foreach($response['output']??[] as $output)foreach($output['content']??[] as $content)if(isset($content['text']))$text=$content['text'];$result=json_decode($text,true,512,JSON_THROW_ON_ERROR);
 $maps=['company'=>['companies',['sector','is_ai','headquarters','founded_year','description','last_round_date','last_round_size','last_round_valuation','valuation_currency','source_name','source_url','as_of_date']], 'ai_company'=>['companies',['sector','headquarters','founded_year','description','last_round_date','last_round_size','last_round_valuation','valuation_currency','source_name','source_url','as_of_date']], 'data_center'=>['data_centers',['category','location','latitude','longitude','owner','builder','power_mw','tenant','financing','status','description','source_name','source_url','as_of_date']], 'pe_firm'=>['private_equity_firms',['strategy','headquarters','description','source_name','source_url','as_of_date']], 'vc_firm'=>['vc_firms',['category','headquarters','description','source_name','source_url','as_of_date']], 'spac'=>['spac_vehicles',['sponsor','raised_date','ipo_size','currency','deadline','status','description','source_name','source_url','as_of_date']]];
 $db=database();$run=$db->prepare('INSERT INTO ai_update_runs(user_id,prompt) VALUES(?,?)');$run->execute([$_SESSION['user_id'],$prompt]);$runId=(int)$db->lastInsertId();$sourceLog=$db->prepare('INSERT IGNORE INTO ai_run_sources(run_id,provider) VALUES(?,?)');$sourceLog->execute([$runId,'Web search']);foreach($licensed as $source){$sourceLog->execute([$runId,$source['provider']]);$db->prepare('UPDATE data_sources SET last_success_at=NOW() WHERE name=?')->execute([$source['provider']]);}$db->beginTransaction();$updated=0;foreach($result['records']??[] as $record){if(!isset($maps[$record['type']]))continue;$data=$record['data'];$type=$record['type'];if(in_array($type,['company','ai_company'],true))$data['sector']??=$record['category'];if($type==='pe_firm')$data['strategy']??=$record['category'];if(in_array($type,['vc_firm','data_center'],true))$data['category']??=$record['category'];if(empty($data['source_url'])||!filter_var($data['source_url'],FILTER_VALIDATE_URL))continue;[$table,$allowed]=$maps[$type];$values=['name'=>$record['name']];if($type==='ai_company')$values['is_ai']=1;foreach($allowed as $column)if(array_key_exists($column,$data))$values[$column]=$data[$column];$values['confidence']='Review';$columns=array_keys($values);$sql="INSERT INTO `$table` (`".implode('`,`',$columns)."`) VALUES (".implode(',',array_fill(0,count($columns),'?')).") ON DUPLICATE KEY UPDATE ".implode(',',array_map(fn($c)=>"`$c`=VALUES(`$c`)",array_slice($columns,1)));$db->prepare($sql)->execute(array_values($values));$updated++;}
 foreach($result['records']??[] as $record){$type=$record['type']??'';$data=$record['data']??[];if(!in_array($type,['vc_investment','pe_ownership'],true)||empty($data['source_url'])||!filter_var($data['source_url'],FILTER_VALIDATE_URL))continue;$company=$db->prepare('SELECT id FROM companies WHERE name=?');$company->execute([$data['company_name']??$record['name']]);$companyId=$company->fetchColumn();if(!$companyId)continue;if($type==='vc_investment'){$firm=$db->prepare('SELECT id FROM vc_firms WHERE name=?');$firm->execute([$data['vc_firm_name']??'']);$firmId=$firm->fetchColumn();if(!$firmId)continue;$db->prepare('INSERT INTO company_vc_investments(company_id,vc_firm_id,round_name,announced_date,amount,currency,is_lead,source_url) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE announced_date=VALUES(announced_date),amount=VALUES(amount),currency=VALUES(currency),is_lead=VALUES(is_lead),source_url=VALUES(source_url)')->execute([$companyId,$firmId,$data['round_name']??'Undisclosed',$data['announced_date']??null,$data['amount']??null,$data['currency']??null,!empty($data['is_lead']),$data['source_url']]);}else{$firm=$db->prepare('SELECT id FROM private_equity_firms WHERE name=?');$firm->execute([$data['pe_firm_name']??'']);$firmId=$firm->fetchColumn();if(!$firmId)continue;$db->prepare('INSERT INTO company_pe_ownership(company_id,pe_firm_id,acquired_date,exited_date,ownership_notes,source_url) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE acquired_date=VALUES(acquired_date),exited_date=VALUES(exited_date),ownership_notes=VALUES(ownership_notes),source_url=VALUES(source_url)')->execute([$companyId,$firmId,$data['acquired_date']??null,$data['exited_date']??null,$data['ownership_notes']??null,$data['source_url']]);}$updated++;}
 $db->commit();$db->prepare("UPDATE ai_update_runs SET status='Completed',records_written=?,completed_at=NOW() WHERE id=?")->execute([$updated,$runId]);echo json_encode(['updated'=>$updated,'run_id'=>$runId]);
} catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();if(isset($db,$runId))$db->prepare("UPDATE ai_update_runs SET status='Failed',error_message=?,completed_at=NOW() WHERE id=?")->execute([substr($e->getMessage(),0,500),$runId]);http_response_code(400);echo json_encode(['error'=>$e->getMessage()]);}
