<?php
declare(strict_types=1);require __DIR__.'/auth.php';requireLogin(true);
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
$resources=[
 'allcompanies'=>['table'=>'companies','columns'=>['name','sector','is_ai','headquarters','founded_year','last_round_date','last_round_size','last_round_valuation','valuation_currency','description','source_name','source_url','as_of_date','confidence']],
 'aicompanies'=>['table'=>'companies','columns'=>['name','sector','headquarters','founded_year','last_round_date','last_round_size','last_round_valuation','valuation_currency','description','source_name','source_url','as_of_date','confidence'],'fixed'=>'`is_ai`=1'],
 'pefirms'=>['table'=>'private_equity_firms','columns'=>['name','strategy','headquarters','description','source_name','source_url','as_of_date','confidence']],
 'vcfirms'=>['table'=>'vc_firms','columns'=>['name','category','headquarters','description','source_name','source_url','as_of_date','confidence']],
 'spacs'=>['table'=>'spac_vehicles','columns'=>['name','sponsor','raised_date','ipo_size','currency','deadline','status','description','source_name','source_url','as_of_date','confidence']],
 'datacenters'=>['table'=>'data_centers','columns'=>['name','category','location','latitude','longitude','owner','builder','power_mw','tenant','financing','status','as_of_date','description','source_name','source_url','confidence']]
];
try{
 $resource=$_GET['resource']??'';if(!isset($resources[$resource])){http_response_code(400);throw new InvalidArgumentException('Unknown resource.');}$d=$resources[$resource];
 $search=trim((string)($_GET['search']??''));$category=trim((string)($_GET['category']??''));$sort=(string)($_GET['sort']??'name');$direction=strtolower((string)($_GET['direction']??'asc'))==='desc'?'DESC':'ASC';if(!in_array($sort,$d['columns'],true))$sort='name';
 $where=isset($d['fixed'])?[$d['fixed']]:[];$params=[];
 if($search!==''){$clauses=[];foreach($d['columns'] as $i=>$column){if(in_array($column,['is_ai','founded_year','last_round_date','last_round_size','last_round_valuation','as_of_date'],true))continue;$key="q$i";$clauses[]="`$column` LIKE :$key";$params[$key]="%$search%";}
  if(in_array($resource,['allcompanies','aicompanies'],true)){$clauses[]='EXISTS(SELECT 1 FROM company_vc_investments i JOIN vc_firms v ON v.id=i.vc_firm_id WHERE i.company_id=companies.id AND v.name LIKE :vcq)';$params['vcq']="%$search%";$clauses[]='EXISTS(SELECT 1 FROM company_pe_ownership o JOIN private_equity_firms p ON p.id=o.pe_firm_id WHERE o.company_id=companies.id AND p.name LIKE :peq)';$params['peq']="%$search%";}$where[]='('.implode(' OR ',$clauses).')';}
 $filterColumn=in_array($resource,['allcompanies','aicompanies'],true)?'sector':($resource==='pefirms'?'strategy':($resource==='spacs'?'status':'category'));if($category!==''&&$category!=='all'){$where[]="`$filterColumn`=:category";$params['category']=$category;}
 $columns=implode(',',array_map(fn($c)=>"`$c`",$d['columns']));$sql="SELECT `id`,$columns FROM `{$d['table']}`".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY `$sort` $direction LIMIT 500";$stmt=database()->prepare($sql);$stmt->execute($params);$records=$stmt->fetchAll();
 if($records){$ids=array_column($records,'id');$ph=implode(',',array_fill(0,count($ids),'?'));
  if(in_array($resource,['allcompanies','aicompanies'],true)){$q=database()->prepare("SELECT i.company_id,v.name,i.round_name,i.announced_date,i.amount,i.currency,i.is_lead FROM company_vc_investments i JOIN vc_firms v ON v.id=i.vc_firm_id WHERE i.company_id IN ($ph) ORDER BY v.name");$q->execute($ids);$vc=[];foreach($q as $row)$vc[$row['company_id']][]=$row;$q=database()->prepare("SELECT o.company_id,p.name,o.acquired_date,o.exited_date,o.ownership_notes FROM company_pe_ownership o JOIN private_equity_firms p ON p.id=o.pe_firm_id WHERE o.company_id IN ($ph) ORDER BY p.name");$q->execute($ids);$pe=[];foreach($q as $row)$pe[$row['company_id']][]=$row;foreach($records as &$r){$r['investors']=$vc[$r['id']]??[];$r['pe_owners']=$pe[$r['id']]??[];}unset($r);}
  if($resource==='vcfirms'){$q=database()->prepare("SELECT i.vc_firm_id,c.id,c.name,c.sector,c.is_ai,i.round_name,i.announced_date FROM company_vc_investments i JOIN companies c ON c.id=i.company_id WHERE i.vc_firm_id IN ($ph) ORDER BY c.name");$q->execute($ids);$by=[];foreach($q as $row)$by[$row['vc_firm_id']][]=$row;foreach($records as &$r){$r['portfolio']=$by[$r['id']]??[];$r['portfolio_count']=count($r['portfolio']);}unset($r);}
  if($resource==='pefirms'){$q=database()->prepare("SELECT o.pe_firm_id,c.id,c.name,c.sector,c.is_ai,o.acquired_date,o.exited_date FROM company_pe_ownership o JOIN companies c ON c.id=o.company_id WHERE o.pe_firm_id IN ($ph) ORDER BY c.name");$q->execute($ids);$by=[];foreach($q as $row)$by[$row['pe_firm_id']][]=$row;foreach($records as &$r){$r['portfolio']=$by[$r['id']]??[];$r['portfolio_count']=count($r['portfolio']);}unset($r);}}
 if($resource==='spacs'){foreach($records as &$record)$record['time_left_days']=(int)((strtotime($record['deadline'])-strtotime(date('Y-m-d')))/86400);unset($record);}
 $catSql="SELECT DISTINCT `$filterColumn` category FROM `{$d['table']}`".(isset($d['fixed'])?' WHERE '.$d['fixed']:'')." ORDER BY `$filterColumn`";$categories=array_column(database()->query($catSql)->fetchAll(),'category');$countSql="SELECT COUNT(*) total,SUM(confidence='Verified') verified,MAX(updated_at) last_sync FROM `{$d['table']}`".(isset($d['fixed'])?' WHERE '.$d['fixed']:'');$stats=database()->query($countSql)->fetch();echo json_encode(compact('records','categories','stats'),JSON_THROW_ON_ERROR);
}catch(Throwable $e){http_response_code(http_response_code()>=400?http_response_code():500);echo json_encode(['error'=>$e instanceof InvalidArgumentException?$e->getMessage():'The data service is temporarily unavailable.']);}
